# Generated by Django 4.1.5 on 2023-02-02 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('FOUR_SEATER', '4 Seats'), ('SIX_SEATER', '6 Seats')], default='FOUR_SEATER', max_length=15)),
                ('max_passengers', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('license_no', models.CharField(default=None, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('rideId', models.AutoField(primary_key=True, serialize=False)),
                ('isSharable', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('destinationArrivalTimeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed')], default='OPEN', max_length=10)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ridesharingapp.driver')),
                ('rideOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_owner', to='ridesharingapp.party')),
                ('rideShared', models.ManyToManyField(blank=True, to='ridesharingapp.party')),
            ],
        ),
    ]
