# Generated by Django 4.1.5 on 2023-01-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('DriverId', models.AutoField(primary_key=True, serialize=False)),
                ('DriverName', models.CharField(max_length=500)),
            ],
        ),
    ]
