# Generated by Django 4.1.5 on 2023-02-04 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='availablePassengers',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='ride',
            name='maxPassengers',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
