# Generated by Django 4.1.5 on 2023-02-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharingapp', '0002_ride_availablepassengers_ride_maxpassengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='maxPassengers',
        ),
        migrations.AddField(
            model_name='driver',
            name='special_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='specialRequests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicleType',
            field=models.CharField(blank=True, choices=[('FOUR_SEATER', '4 Seats'), ('SIX_SEATER', '6 Seats')], max_length=15, null=True),
        ),
    ]
