# Generated by Django 4.1.5 on 2023-01-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ridesharingapp', '0002_delete_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('RideId', models.AutoField(primary_key=True, serialize=False)),
                ('Source', models.CharField(max_length=500)),
                ('Destination', models.CharField(max_length=500)),
            ],
        ),
    ]
