# Generated by Django 4.1.5 on 2023-01-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharingapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('rideId', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('RIDING', 'RIDING'), ('FINISHED', 'FINISHED')], default='NEW', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('emailId', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rides',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ridesharingapp.user')),
                ('vehicle', models.CharField(max_length=500)),
            ],
            bases=('ridesharingapp.user',),
        ),
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='ridesharingapp.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='rideShared',
            field=models.ManyToManyField(blank=True, to='ridesharingapp.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ridesharingapp.driver'),
        ),
    ]
